/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_server_mia_Interface */

#ifndef _Included_com_android_server_mia_Interface
#define _Included_com_android_server_mia_Interface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_android_server_mia_Interface_CR_LIMITED_APP
#define com_android_server_mia_Interface_CR_LIMITED_APP 1L
#undef com_android_server_mia_Interface_CR_LIMITED_WEB
#define com_android_server_mia_Interface_CR_LIMITED_WEB 2L
#undef com_android_server_mia_Interface_CR_LIMITED_IP
#define com_android_server_mia_Interface_CR_LIMITED_IP 4L
#undef com_android_server_mia_Interface_FLAG_FILTER_DEFAULT
#define com_android_server_mia_Interface_FLAG_FILTER_DEFAULT 0L
#undef com_android_server_mia_Interface_FLAG_FILTER_WHITE
#define com_android_server_mia_Interface_FLAG_FILTER_WHITE 1L
#undef com_android_server_mia_Interface_FLAG_FILTER_BLACK
#define com_android_server_mia_Interface_FLAG_FILTER_BLACK 2L
/*
 * Class:     com_android_server_mia_Interface
 * Method:    Init
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_server_mia_Interface_Init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_android_server_mia_Interface
 * Method:    SetNetFilterRule
 * Signature: (ILjava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_server_mia_Interface_SetNetFilterRule
  (JNIEnv *, jclass, jint, jstring, jint, jint);

/*
 * Class:     com_android_server_mia_Interface
 * Method:    Release
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_server_mia_Interface_Release
  (JNIEnv *, jclass);

/*
 * Class:     com_android_server_mia_Interface
 * Method:    ClearUids
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_server_mia_Interface_ClearUids
  (JNIEnv *, jclass);

/*
 * Class:     com_android_server_mia_Interface
 * Method:    ClearIpHosts
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_server_mia_Interface_ClearIpHosts
  (JNIEnv *, jclass);

/*
 * Class:     com_android_server_mia_Interface
 * Method:    SetDefaultLimited
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_server_mia_Interface_SetDefaultLimited
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_android_server_mia_Interface
 * Method:    Enable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_server_mia_Interface_Enable
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
